[versions]
agp = "9.2.1"
play-services-wearable = "19.0.0"
androidx-wear-watchface-complications = "1.3.0"
coroutines = "1.9.0"

[libraries]
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "play-services-wearable" }
androidx-watchface-complications-data = { group = "androidx.wear.watchface", name = "watchface-complications-data", version.ref = "androidx-wear-watchface-complications" }
androidx-watchface-complications-datasource = { group = "androidx.wear.watchface", name = "watchface-complications-data-source", version.ref = "androidx-wear-watchface-complications" }
androidx-watchface-complications-datasource-ktx = { group = "androidx.wear.watchface", name = "watchface-complications-data-source-ktx", version.ref = "androidx-wear-watchface-complications" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
